/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface OracleRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ethUsdFeed"
      | "ftse100Feed"
      | "gbpUsdFeed"
      | "getEthUsdPrice"
      | "getFtse100Value"
      | "getGbpUsdPrice"
      | "getGoldUsdPrice"
      | "goldUsdFeed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ethUsdFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ftse100Feed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gbpUsdFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEthUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFtse100Value",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGbpUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGoldUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "goldUsdFeed",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ethUsdFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ftse100Feed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gbpUsdFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEthUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFtse100Value",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGbpUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGoldUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "goldUsdFeed",
    data: BytesLike
  ): Result;
}

export interface OracleRouter extends BaseContract {
  connect(runner?: ContractRunner | null): OracleRouter;
  waitForDeployment(): Promise<this>;

  interface: OracleRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ethUsdFeed: TypedContractMethod<[], [string], "view">;

  ftse100Feed: TypedContractMethod<[], [string], "view">;

  gbpUsdFeed: TypedContractMethod<[], [string], "view">;

  getEthUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;

  getFtse100Value: TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; updatedAt: bigint }],
    "view"
  >;

  getGbpUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;

  getGoldUsdPrice: TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;

  goldUsdFeed: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ethUsdFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ftse100Feed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gbpUsdFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEthUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFtse100Value"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { value: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGbpUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGoldUsdPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { price: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "goldUsdFeed"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
