/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOracleRouter,
  IOracleRouterInterface,
} from "../../../contracts/interfaces/IOracleRouter";

const _abi = [
  {
    inputs: [],
    name: "getEthUsdPrice",
    outputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFtse100Value",
    outputs: [
      {
        internalType: "int256",
        name: "value",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGbpUsdPrice",
    outputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGoldUsdPrice",
    outputs: [
      {
        internalType: "int256",
        name: "price",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "updatedAt",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IOracleRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IOracleRouterInterface {
    return new Interface(_abi) as IOracleRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IOracleRouter {
    return new Contract(address, _abi, runner) as unknown as IOracleRouter;
  }
}
