/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetVault } from "./AssetVault";
export type { IERC7943NonFungible } from "./IERC7943NonFungible";
