/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AssetShares } from "./AssetShares";
export type { IERC7943MultiToken } from "./IERC7943MultiToken";
