/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ierc7943Sol from "./Ierc7943.sol";
export type { ierc7943Sol };
export type { IOracleRouter } from "./IOracleRouter";
