/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC7943MultiToken__factory } from "./IERC7943MultiToken__factory";
export { IERC7943NonFungible__factory } from "./IERC7943NonFungible__factory";
