/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetSharesSol from "./AssetShares.sol";
export type { assetSharesSol };
import type * as assetVaultSol from "./AssetVault.sol";
export type { assetVaultSol };
export type { AssetUserAllowList } from "./AssetUserAllowList";
