/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IERC7943NonFungibleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canTransact"
      | "canTransfer"
      | "forcedTransfer"
      | "isFrozen"
      | "isUserAllowed"
      | "setFrozenToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ForcedTransfer" | "Frozen"): EventFragment;

  encodeFunctionData(
    functionFragment: "canTransact",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forcedTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isFrozen",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isUserAllowed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFrozenToken",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "canTransact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFrozenToken",
    data: BytesLike
  ): Result;
}

export namespace ForcedTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, tokenId: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FrozenEvent {
  export type InputTuple = [user: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [user: string, tokenId: bigint];
  export interface OutputObject {
    user: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IERC7943NonFungible extends BaseContract {
  connect(runner?: ContractRunner | null): IERC7943NonFungible;
  waitForDeployment(): Promise<this>;

  interface: IERC7943NonFungibleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canTransact: TypedContractMethod<
    [user: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  canTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;

  forcedTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  isFrozen: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  isUserAllowed: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  setFrozenToken: TypedContractMethod<
    [tokenId: BigNumberish, frozen: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canTransact"
  ): TypedContractMethod<
    [user: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "forcedTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isUserAllowed"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "setFrozenToken"
  ): TypedContractMethod<
    [tokenId: BigNumberish, frozen: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ForcedTransfer"
  ): TypedContractEvent<
    ForcedTransferEvent.InputTuple,
    ForcedTransferEvent.OutputTuple,
    ForcedTransferEvent.OutputObject
  >;
  getEvent(
    key: "Frozen"
  ): TypedContractEvent<
    FrozenEvent.InputTuple,
    FrozenEvent.OutputTuple,
    FrozenEvent.OutputObject
  >;

  filters: {
    "ForcedTransfer(address,address,uint256)": TypedContractEvent<
      ForcedTransferEvent.InputTuple,
      ForcedTransferEvent.OutputTuple,
      ForcedTransferEvent.OutputObject
    >;
    ForcedTransfer: TypedContractEvent<
      ForcedTransferEvent.InputTuple,
      ForcedTransferEvent.OutputTuple,
      ForcedTransferEvent.OutputObject
    >;

    "Frozen(address,uint256)": TypedContractEvent<
      FrozenEvent.InputTuple,
      FrozenEvent.OutputTuple,
      FrozenEvent.OutputObject
    >;
    Frozen: TypedContractEvent<
      FrozenEvent.InputTuple,
      FrozenEvent.OutputTuple,
      FrozenEvent.OutputObject
    >;
  };
}
