/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC7943MultiToken } from "./IERC7943MultiToken";
export type { IERC7943NonFungible } from "./IERC7943NonFungible";
